### ISSUE TITLE
Program shows wrong ebooks

### ISSUE THREAD

**Issue by TheWutz** [hampoelz/Digi4School2Pdf#9]
I have several music education books (Musix 1-4, Musik aktiv 1-4, Wege zur Musik 1 & 2, Spielpläne). When I open them in browser, they are fine. In the downloader all of them get displayed as pages from A Midsummer Night's dream. Strangely enough, they have the right amount of pages.

**Comment by hampoelz** [comment]
Hey @TheWutz thanks for the report!

- When you open the book, does it take you to a page like oebv, scook or helbling-ezone?
- Does the downloader show any erros or something related?
- Is it possible for you to upload a screenshot of a broken page?

**Comment by Markus04122** [comment]
I have the same problem as TheWutz!

**Comment by hampoelz** [comment]
@TheWutz Is the book you're trying to download part of the oebv, scook or helbling-ezone library?

**Comment by Markus04122** [comment]
Yes, it is part of the oebv library and I have no problems to download the page but the page doesn't contain the content of the book, it's just a dialogue.

**Comment by hampoelz** [comment]
That explains a lot! It's because the downloader currently doesn't support downloading books from oebv. I'll add support for oebv and other libraries soon as mentioned in #1 or #5.

However, It's weird because the downloader should indicate that there is no book to download when trying to download from an unsupported library.

@Markus04122 Does this behavior occur with all of your books from oebv or just with some?

**Comment by Markus04122** [comment]
Yes, this behavior occures with all of my books EXCEPT "Lösungswege 6", "Lösungswege 7" and "PrimeTime 6".

**Comment by hampoelz** [comment]
Hmm thats interresting.

Would it be possible to send me the code for the page for one of these books?

To do this, just follow the steps below: 
1. Open the book and **toggle the developer tools** under the menu item `View` in the top bar of the downloader 
2. In the opened window, select the `Elements` tab and you will see something like this: 
```html
<!DOCTYPE html>
<head>...</head>

<body style="...">
...
```
3. Right click on the `<body>` tag and select `Copy` -> ` Copy outerHTML`
4. Open https://pastebin.com/ in your browser, paste the code, click `Create New Paste` and send the link

**Comment by Markus04122** [comment]
https://pastebin.com/7qq6BwZr
I hope it will work

**Comment by hampoelz** [comment]
Perfect thank you.
I'll check this in the next few weeks, when I've time, and then get back to you.

**Comment by hampoelz** [comment]
@TheWutz @TheWutz When you open the book with the downloader, does the dialog look something like the image below? But when you open the book in the browser, it displays correctly, right? 

![image](https://user-images.githubusercontent.com/28979769/150655099-d669a09b-9ca7-4a0b-abc8-69ea2d3b7662.png)

**Comment by Markus04122** [comment]
Yes, if I use Digi4School2Pdf to open a book all pages look like a dialogue.
And if I use Digi4School on the browser everything is normal.

**Comment by hampoelz** [comment]
This is because the downloader tries to cache the pages by default to improve load times, but the libraries try to prevent the real pages from being cached (probably for security reasons), so those random dialogs get cached.

To work around this problem, you can toggle the developer tools, go to the "Network" tab and check the "Disable cache" option and refresh the page.

I will fix this issue in the upcoming version which will be released next week.

**Comment by hampoelz** [comment]
Fixed in latest version, you can update from store.
